### PR TITLE
add icon for just

### PR DESCRIPTION
**Pull request by sleao**
Added an icon for [justfiles](https://github.com/casey/just).
It's actually the same as Makefile, since just doesn't have a logo.

### CODE REVIEW

**Comment by prazdevs** [comment]
there's no need to duplicate the icon, you can just add the justfiles associations to the makefile icon

**Comment by sleao** [comment]
I duplicated just in case anyone decides to update it in the future. Adding justfile to `files.ts` and keeping the change on `extensions.ts` should work, right?

**Comment by prazdevs** [comment]
just add justfiles or just where needed to the `makefile` property of each association file needed

**Comment by nekowinston** [comment]
It's worth noting that Just doesn't have an official icon yet, but there is one that's used elsewhere (the `:` logo)

See https://github.com/casey/just/issues/1255

**Comment by prazdevs** [comment]
giga merged v1, will arrive soon with just icon

**Pull request closed without merging**
