### PR TITLE
Added ANTLRv4 icon

### LINKED ISSUE #65: [Icon Request] ANTLRv4
Extensions: `g4`

SVG Logo:

```svg
<?xml version="1.0" encoding="utf-8"?>
<svg width="800px" height="800px" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
    <path d="M14.177,7.278a2.08,2.08,0,0,1,3.041-.8A3.571,3.571,0,0,1,18.2,8.022c1.356,3.122,2.9,6.165,4.119,9.345.645,1.5,1.429,2.938,1.994,4.468a1.455,1.455,0,0,1-2.258,1.376c-2.8-1.572-5.628-3.094-8.385-4.731,2.009.008,4.018-.008,6.025.013a19.707,19.707,0,0,0-1.288-2.918c-.781-1.858-1.6-3.7-2.358-5.565a9.783,9.783,0,0,0-1.032,2.125c-1.3,3.182-2.87,6.241-4.136,9.435-.281.59-.424,1.344-1.035,1.69a1.447,1.447,0,0,1-2.094-.738c-.241-.61.151-1.2.382-1.743.779-1.725,1.645-3.413,2.283-5.2C11.65,12.8,12.916,10.041,14.177,7.278Z" style="fill:#fefefe"/>
    <path d="M13.817,2.2A13.923,13.923,0,0,1,29.526,12.549a13.733,13.733,0,0,1-2.082,11.519A14.074,14.074,0,0,1,7.738,27.293a13.852,13.852,0,0,1-5.615-9.483A14.152,14.152,0,0,1,3.451,9.85,13.961,13.961,0,0,1,13.817,2.2m.359,5.08c-1.261,2.762-2.526,5.525-3.762,8.3-.638,1.786-1.5,3.473-2.283,5.2-.231.542-.623,1.133-.382,1.743a1.447,1.447,0,0,0,2.094.738c.61-.347.753-1.1,1.035-1.69,1.266-3.194,2.833-6.253,4.136-9.435a9.783,9.783,0,0,1,1.032-2.125c.756,1.868,1.577,3.707,2.358,5.565a19.707,19.707,0,0,1,1.288,2.918c-2.007-.02-4.016-.005-6.025-.013,2.757,1.637,5.588,3.159,8.385,4.731a1.455,1.455,0,0,0,2.258-1.376c-.565-1.529-1.349-2.971-1.994-4.468-1.22-3.179-2.762-6.223-4.119-9.345a3.571,3.571,0,0,0-.982-1.544A2.08,2.08,0,0,0,14.177,7.278Z" style="fill:#e44a32"/>
</svg>
```

image

The color probably needs to be toned down to match the pastel palette.
Also: the red circle could be simpler, I guess (`<circle .../>`)

### PR DESCRIPTION
**Pull request by ricardoboss**
Fixes #65

### CODE REVIEW

**Comment by prazdevs** [comment]
hi thanks for the contribution, however icon doesnt fit the style guidelines, i'll close the PR but keep the issue open and eventually do it :)

**Comment by ricardoboss** [comment]
But... the icon is 100 by 100. Where are the style guidelines?

**Comment by ricardoboss** [comment]
By the way: I put a lot of effort into editing the icon to match the style of the other icons and simply closing this PR without giving me feedback I can build upon is quite rude IMHO.

**Comment by prazdevs** [comment]
never meant to, i just struggle with having PRs open that won't be merged atm so i try to avoid being overwhelmed. it's in the works to add a proper contributing guide with guidelines, but we're also smh working on changing them and the way the extension is (to add more customization for example). i added context on the issue you opened and you're still very welcome to re submit a fitting one

**Comment by ricardoboss** [comment]
I updated the icon according to your suggestions. I also simplified the source file so it is easier to read.

**Comment by ricardoboss** [comment]
This is how it looks in use in VS Code: 
image

**Comment by quentinguidee** [comment]
@ricardoboss I'm not maintainer of this repo, but when comparing to other icons this still doesn't seem to follow the icons style: All lines should have the same weight, and the "A" here seems 3x more bold. The entire goal of this icons pack is to make all icons more uniform and coherent together; so maybe you can try reusing the "A" from the icon at the top right in this screen, and mirror it?

image

**Comment by ricardoboss** [comment]
I see what you mean, yeah. I tried to stay true to the original logo, but it may be better to adjust it even more. Let me work on it a bit more

**Comment by ricardoboss** [comment]
@quentinguidee @prazdevs what do you think?

**Comment by prazdevs** [comment]
giga merged v1, and antlr icon will be available ! closing this

**Pull request closed without merging**
