### PR TITLE
feat: add liquid icon

### LINKED ISSUE #52: [Icon request] Liquid file icons
Please add support for Shopify Liquid (.liquid) files. Often times they look like a raindrop or wavy lines.

### PR DESCRIPTION
**Pull request by nekowinston**
Closes #52

@brady-sewall if there are any extra files/extensions this icon should cover, please let me know.

### CODE REVIEW

**Comment by brady-sewall** [comment]
> Closes #52
> 
> @brady-sewall if there are any extra files/extensions this icon should cover, please let me know.

The only other file type that is missing is dot files (showing a generic file type). Not a big deal, unless you feel like customizing. 
image

**Comment by nekowinston** [comment]
I added the [icon association](https://github.com/catppuccin/vscode-icons/pull/53/files#diff-5853110db3bd52da7f1c2a123d9c675e3969ae01ca22ee415cd691ebfd4b6f73R344) for `.liquidrc` and `.liquidrc.json`, I think `.shopifyignore`/other Shopify files would warrant their own icons.

`.tool-versions` is asdf, right?

**Comment by brady-sewall** [comment]
> I added the [icon association](https://github.com/catppuccin/vscode-icons/pull/53/files#diff-5853110db3bd52da7f1c2a123d9c675e3969ae01ca22ee415cd691ebfd4b6f73R344) for `.liquidrc` and `.liquidrc.json`, I think `.shopifyignore`/other Shopify files would warrant their own icons.
> 
> `.tool-versions` is asdf, right?

I'm not sure if it's asdf. Inside just lists the nodejs version.

**Comment by brady-sewall** [comment]
@prazdevs I updated to the latest build as of today, restarted VS Code and it looks like the liquid and dot files are still unthemed. Am I mistaken that this commit was included in the build today?

image

**Comment by prazdevs** [comment]
https://github.com/catppuccin/vscode-icons/commits/main

**Comment by j-moltz** [comment]
Thank you for creating this icon! Something seems to have happened between the end of October commits when this icon was created and added and the December commits, as the liquid icon is no longer part of the set. Could it be re-added?

**Pull request merged**
